### ISSUE TITLE
bs4.FeatureNotFound

### ISSUE THREAD

**Issue by rtayne** [toutils/todbmanager#1]
When I ran todbmanager.py I got bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

I had to also  python -m pip install lxml

**Comment by toutils** [comment]
I just checked on windows 7 and got the same thing, but I recall using lxml in the code and having to install it on linux; I'm updating the instructions. Installing lxml with pip (or with the package manager on linux) solves this particular problem. lxml doesn't have to be used, I haven't benchmarked it, but it's supposed to be considerably faster than the default. I should probably add a check and make it optional at some point.

**Comment by toutils** [comment]
https://github.com/toutils/todbmanager/commit/599ce162bfe4ae01d2de0e0017dc562e36759567

**Comment by toutils** [comment]
Commit https://github.com/toutils/todbmanager/commit/c50dcc792c263d6c1d66233de2c6d67e8a8778cc
